#!/bin/bash

# Tor Client app for YunoHost
# Copyright (C) 2015 Emile Morel <emile@bleuchtang.fr>
# Copyright (C) 2015 Julien Vaubourg <julien@vaubourg.com>
# Contribute at https://github.com/labriqueinternet/torclient_ynh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Retrieve arguments
domain=$(sudo yunohost app setting torclient domain)

# The End
sudo systemctl stop ynh-torclient
sudo systemctl disable ynh-torclient
sudo yunohost service remove ynh-torclient
sudo rm -f /etc/systemd/system/ynh-torclient.service /usr/local/bin/ynh-torclient
sudo rm -f /tmp/.ynh-torclient-*

# Update firewall for DHCP
sudo yunohost firewall disallow UDP 9053
sudo yunohost firewall disallow TCP 9040

# Remove confs
sudo rm -f /etc/tor/torrc.tpl
sudo rm -f /etc/nginx/conf.d/${domain}.d/torclient.conf
sudo rm -f /etc/php5/fpm/pool.d/torclient.conf

# Restart services
sudo systemctl restart php5-fpm
sudo systemctl reload nginx

# Remove sources
sudo rm -rf /var/www/torclient/

sudo rm -rf /etc/apt/sources.list.d/torproject.list
sudo apt-key del 0xee8cbc9e886ddd89
sudo apt-get update

exit 0
