#!/bin/bash

ynh_setting() {
  app=${1}
  setting=${2}

  sudo grep "^${setting}:" "/etc/yunohost/apps/${app}/settings.yml" | sed s/^[^:]\\+:\\s*[\"\']\\?// | sed s/\\s*[\"\']\$//
}

domain=$(ynh_setting torclient domain)
path=$(ynh_setting torclient path)

export TORCLIENT_UPGRADE=1
sudo bash /etc/yunohost/apps/torclient/scripts/remove &> /dev/null
bash ./install "${domain}" "${path}"

sudo systemctl start ynh-torclient

exit 0
